# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-iam-assumed-roles
  description: Terraform Module for Assumed Roles on AWS with IAM Groups Requiring MFA
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-modules, aws, iam-role, sts, mfa, iam, assume-role

